### ISSUE TITLE
WiP: Replace nodejs via chromium headless shell add needed Userland Wrappers

### ISSUE THREAD

**Issue by lemanschik** [lemanschik/awesome#12]
# Replace nodejs via chromium headless shell add needed Userland Wrappers

## Why?
see: https://github.com/lemanschik/why-you-should-switch-away-from-npm-nodejs

## Roadmap
- [ ] Teach and Educate at last 5 Linux Developers to a state where they can build with confidence. 
  - [ ] use WiP Build Process Details if needed: https://github.com/lemanschik/awesome/issues/11
- [ ] Enable Headless Build via Just Runtime.
- [ ] Enable Headless Build via Declarativ Chromium Platform build
- [ ] Enable codeMod GN Ninja Build integration.
- [ ] Enable blockly based Visual Chromium Platform build tool VCP Build a Chromium Powered Chromium Build tool based on a Composed Chromium Runtime that executes your builds in a distributed fashion using all Stealify Lang Compiler guard Rails and codeMod abilities.
- [ ] Enable CPP2 Compiler 
- [ ] Enable CPP2 Code Mods.
